<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 C:\Users\marti\Desktop\prstovka\static\models\Model.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName =
    | 'ActionLetterA'
    | 'ActionLetterAA'
    | 'ActionLetterAd'
    | 'ActionLetterB'
    | 'ActionLetterBB'
    | 'ActionLetterC'
    | 'ActionLetterCc'
    | 'ActionLetterCC'
    | 'ActionLetterCh'
    | 'ActionLetterChCh'
    | 'ActionLetterD'
    | 'ActionLetterDc'
    | 'ActionLetterDD'
    | 'ActionLetterE'
    | 'ActionLetterEc'
    | 'ActionLetterEd'
    | 'ActionLetterEE'
    | 'ActionLetterF'
    | 'ActionLetterFF'
    | 'ActionLetterG'
    | 'ActionLetterGG'
    | 'ActionLetterH'
    | 'ActionLetterHH'
    | 'ActionLetterI'
    | 'ActionLetterId'
    | 'ActionLetterII'
    | 'ActionLetterJ'
    | 'ActionLetterJJ'
    | 'ActionLetterK'
    | 'ActionLetterKK'
    | 'ActionLetterL'
    | 'ActionLetterLL'
    | 'ActionLetterM'
    | 'ActionLetterMM'
    | 'ActionLetterN'
    | 'ActionLetterNc'
    | 'ActionLetterNN'
    | 'ActionLetterO'
    | 'ActionLetterOd'
    | 'ActionLetterOO'
    | 'ActionLetterP'
    | 'ActionLetterPP'
    | 'ActionLetterQ'
    | 'ActionLetterR'
    | 'ActionLetterRc'
    | 'ActionLetterRR'
    | 'ActionLetterS'
    | 'ActionLetterSc'
    | 'ActionLetterSS'
    | 'ActionLetterT'
    | 'ActionLetterTc'
    | 'ActionLetterTT'
    | 'ActionLetterU'
    | 'ActionLetterUd'
    | 'ActionLetterUU'
    | 'ActionLetterV'
    | 'ActionLetterVV'
    | 'ActionLetterW'
    | 'ActionLetterWW'
    | 'ActionLetterX'
    | 'ActionLetterXX'
    | 'ActionLetterY'
    | 'ActionLetterYd'
    | 'ActionLetterYY'
    | 'ActionLetterZ'
    | 'ActionLetterZc'
    | 'ActionLetterZZ'
    | 'ActionRest'
    | 'ActionRestToTransition'
    | 'PoseFive'
    | 'PoseLetterA'
    | 'PoseLetterB'
    | 'PoseLetterC'
    | 'PoseLetterCH'
    | 'PoseLetterD'
    | 'PoseLetterE'
    | 'PoseLetterF'
    | 'PoseLetterG'
    | 'PoseLetterH'
    | 'PoseLetterI'
    | 'PoseLetterJ'
    | 'PoseLetterK'
    | 'PoseLetterL'
    | 'PoseLetterM'
    | 'PoseLetterN'
    | 'PoseLetterO'
    | 'PoseLetterP'
    | 'PoseLetterQ'
    | 'PoseLetterR'
    | 'PoseLetterS'
    | 'PoseLetterT'
    | 'PoseLetterU'
    | 'PoseLetterV'
    | 'PoseLetterW'
    | 'PoseLetterX'
    | 'PoseLetterY'
    | 'PoseLetterZ'
    | 'PoseNumber5'
    | 'PosePositionRest'
    | 'PosePositionTransition'
    | 'KeyAction'
  type GLTFResult = {
    nodes: {
      Ch22_Eyelashes: THREE.SkinnedMesh
      Ch22_Hair: THREE.SkinnedMesh
      Ch22_Pants: THREE.SkinnedMesh
      Ch22_Shirt: THREE.SkinnedMesh
      Ch22_Sneakers: THREE.SkinnedMesh
      Ch22_Body: THREE.SkinnedMesh
      mixamorig2Hips: THREE.Bone
    }
    materials: {
      Ch22_hair: THREE.MeshStandardMaterial
      Ch22_body: THREE.MeshStandardMaterial
      Ch22_body: THREE.MeshStandardMaterial
    }
  }

  //const gltf = useGltf<GLTFResult>('/models/Model.glb')
  //use draco
  export const gltf = useGltf<GLTFResult>('/models/Model.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <T is={gltf.nodes.mixamorig2Hips} />
        <T.SkinnedMesh
          name="Ch22_Eyelashes"
          geometry={gltf.nodes.Ch22_Eyelashes.geometry}
          material={gltf.materials.Ch22_hair}
          skeleton={gltf.nodes.Ch22_Eyelashes.skeleton}
        />
        <T.SkinnedMesh
          name="Ch22_Hair"
          geometry={gltf.nodes.Ch22_Hair.geometry}
          material={gltf.materials.Ch22_hair}
          skeleton={gltf.nodes.Ch22_Hair.skeleton}
        />
        <T.SkinnedMesh
          name="Ch22_Pants"
          geometry={gltf.nodes.Ch22_Pants.geometry}
          material={gltf.materials.Ch22_body}
          skeleton={gltf.nodes.Ch22_Pants.skeleton}
        />
        <T.SkinnedMesh
          name="Ch22_Shirt"
          geometry={gltf.nodes.Ch22_Shirt.geometry}
          material={gltf.materials.Ch22_body}
          skeleton={gltf.nodes.Ch22_Shirt.skeleton}
        />
        <T.SkinnedMesh
          name="Ch22_Sneakers"
          geometry={gltf.nodes.Ch22_Sneakers.geometry}
          material={gltf.materials.Ch22_body}
          skeleton={gltf.nodes.Ch22_Sneakers.skeleton}
        />
        <T.SkinnedMesh
          name="Ch22_Body"
          geometry={gltf.nodes.Ch22_Body.geometry}
          material={gltf.materials.Ch22_body}
          skeleton={gltf.nodes.Ch22_Body.skeleton}
          morphTargetDictionary={gltf.nodes.Ch22_Body.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.Ch22_Body.morphTargetInfluences}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
